server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hotelmanager?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: root
        password: Admin123!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format-sql: true
        show-sql: true
        database: MYSQL
        hibernate:
            ddl-auto: none
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 914995899417-2rhh0rmm4krt39cg5dom1nj53ob4rvec.apps.googleusercontent.com
                        client-secret: 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